//! Correctness against the Kymatio oracle (VDS-1 section 12.1).
//!
//! Fixtures: `oracles/fixtures/case*.json`, generated by
//! `oracles/kymatio_fixtures.py` (Kymatio 0.3.0, numpy, binary64). For each
//! scattering order m the error is
//!
//! ```text
//! err_m = max_{paths of order m, positions} |ours - ref| / max |ref|
//! ```
//!
//! and must not exceed the stated tolerance: `TOL_FULLRES` against the
//! full-resolution reference (same algorithm, binary64), `TOL_KYMATIO_CORE`
//! against Kymatio's own 2-D cascade (intermediate subsampling, aliasing).

use std::path::Path;

use serde_json::Value;
use vikshep_cpu::CpuBackend;
use vikshep_scatter::{Group, PadPolicy, ScatterConfig, Scattering};

/// Stated tolerance against the full-resolution binary64 reference.
const TOL_FULLRES: f64 = 2e-6;
/// Stated tolerance against Kymatio's own 2-D cascade, per order (0, 1, 2).
const TOL_KYMATIO_CORE: [f64; 3] = [2e-6, 0.05, 0.06];

fn hex_bytes(s: &str) -> Vec<u8> {
    (0..s.len() / 2)
        .map(|i| u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap())
        .collect()
}

fn parse_config(c: &Value) -> ScatterConfig {
    let pads: Vec<PadPolicy> = c["pad"]
        .as_array()
        .unwrap()
        .iter()
        .map(|p| match p.as_str().unwrap() {
            "circular" => PadPolicy::Circular,
            "zero_pad" => PadPolicy::ZeroPad,
            other => panic!("pad {other}"),
        })
        .collect();
    let group = match c["group"].as_str().unwrap() {
        "trivial" => Group::Trivial,
        _ => Group::So2Relative,
    };
    ScatterConfig {
        dim: c["dim"].as_u64().unwrap() as usize,
        group,
        j: c["J"].as_u64().unwrap() as u32,
        q: c["Q"].as_u64().unwrap() as u32,
        l: c["L"].as_u64().unwrap() as u32,
        max_order: 2,
        pad: pads,
        shape: c["shape"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_u64().unwrap() as usize)
            .collect(),
        carrier_cutoff: 1,
    }
}

/// Per-order relative error of `ours` against `reference`.
fn errors(ours: &[f32], reference: &[f64], orders: &[u32], out_len: usize) -> [f64; 3] {
    let mut num = [0.0f64; 3];
    let mut den = [0.0f64; 3];
    for (p, &o) in orders.iter().enumerate() {
        for s in 0..out_len {
            let i = p * out_len + s;
            num[o as usize] = num[o as usize].max((f64::from(ours[i]) - reference[i]).abs());
            den[o as usize] = den[o as usize].max(reference[i].abs());
        }
    }
    [0, 1, 2].map(|o| if den[o] == 0.0 { 0.0 } else { num[o] / den[o] })
}

#[test]
fn matches_kymatio_within_stated_tolerance() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../oracles/fixtures");
    let mut files: Vec<_> = std::fs::read_dir(&dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .collect();
    files.sort();
    assert!(files.len() >= 20, "expected at least 20 oracle fixtures");
    let backend = CpuBackend::new();
    let mut worst_full = [0.0f64; 3];
    let mut worst_core = [0.0f64; 3];
    for f in &files {
        let doc: Value = serde_json::from_str(&std::fs::read_to_string(f).unwrap()).unwrap();
        let cfg = parse_config(&doc["config"]);
        let x: Vec<f32> = hex_bytes(doc["input_f32_le_hex"].as_str().unwrap())
            .chunks_exact(4)
            .map(|b| f32::from_le_bytes(b.try_into().unwrap()))
            .collect();
        let sc = Scattering::new(cfg.clone()).unwrap();
        let out = sc.run(&backend, &x).unwrap();
        let orders: Vec<u32> = out.paths.iter().map(|p| p.order).collect();
        for (name, r) in doc["references"].as_object().unwrap() {
            let paths = r["paths"].as_array().unwrap();
            assert_eq!(paths.len(), out.paths.len(), "{f:?}: path count");
            for (p, ours) in paths.iter().zip(&out.paths) {
                let p: Vec<u64> = p
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_u64().unwrap())
                    .collect();
                assert_eq!(p[0], u64::from(ours.order), "{f:?}: order");
                let j: Vec<u64> = ours.j.iter().map(|&v| u64::from(v)).collect();
                assert_eq!(&p[1..1 + j.len()], &j[..], "{f:?}: scales");
                let t: Vec<u64> = ours.theta.iter().map(|&v| u64::from(v)).collect();
                assert_eq!(&p[1 + j.len()..], &t[..], "{f:?}: orientations");
            }
            let reference: Vec<f64> = hex_bytes(r["values_f64_le_hex"].as_str().unwrap())
                .chunks_exact(8)
                .map(|b| f64::from_le_bytes(b.try_into().unwrap()))
                .collect();
            assert_eq!(reference.len(), out.coefficients.len());
            let e = errors(&out.coefficients, &reference, &orders, out.out_len());
            println!(
                "{} {:<12} dim={} shape={:?} J={} Q={} L={} pad={:?} {:?}: err0={:.2e} err1={:.2e} err2={:.2e}",
                f.file_name().unwrap().to_string_lossy(),
                name,
                cfg.dim,
                cfg.shape,
                cfg.j,
                cfg.q,
                cfg.l,
                cfg.pad,
                cfg.group,
                e[0],
                e[1],
                e[2]
            );
            let (tol, worst) = if name == "fullres" {
                ([TOL_FULLRES; 3], &mut worst_full)
            } else {
                (TOL_KYMATIO_CORE, &mut worst_core)
            };
            for o in 0..3 {
                worst[o] = worst[o].max(e[o]);
                assert!(
                    e[o] <= tol[o],
                    "{f:?} {name}: order {o} error {:.3e} > {:.1e}",
                    e[o],
                    tol[o]
                );
            }
        }
    }
    println!("worst fullres: {worst_full:?}; worst kymatio_core: {worst_core:?}");
}
