//! Accuracy of `vikshep-detmath` against correctly rounded mpmath references.
//!
//! The fixture is generated by `scripts/gen_detmath_fixtures.py`. The error of
//! one evaluation is the distance, in units in the last place, between the
//! computed value and the correctly rounded reference (0 = correctly rounded).
//! The maximum per function and the count of non-correctly-rounded results
//! are asserted exactly, so the figures recorded in `spec/VDS-1.md` section 4
//! cannot silently drift.

use std::collections::BTreeMap;

const FIXTURE: &str = include_str!("fixtures/mpmath_reference.txt");

/// (function, precision) -> (max ulp error, number of results not correctly rounded)
/// Recorded measurement; update `spec/VDS-1.md` together with this table.
const RECORDED: &[(&str, &str, u64, usize)] = &[
    ("cos", "f32", 0, 0),
    ("cos", "f64", 1, 39),
    ("exp", "f32", 0, 0),
    ("exp", "f64", 1, 143),
    ("ln", "f32", 0, 0),
    ("ln", "f64", 1, 4),
    ("sin", "f32", 1, 1),
    ("sin", "f64", 1, 41),
];

/// Map a float's bits (sign bit at position `sign_bit`) onto a monotonic
/// integer line, negative values below positive ones and -0 one step below
/// +0, so that the difference of two mapped values counts ulps.
fn ordered(bits: u64, sign_bit: u32) -> i128 {
    let magnitude = i128::from(bits & !(1u64 << sign_bit));
    if (bits >> sign_bit) & 1 == 1 {
        -magnitude - 1
    } else {
        magnitude
    }
}

fn ulp_distance(computed: u64, expected: u64, sign_bit: u32) -> u64 {
    let d = (ordered(computed, sign_bit) - ordered(expected, sign_bit)).unsigned_abs();
    u64::try_from(d).unwrap()
}

#[test]
fn accuracy_against_mpmath() {
    let mut stats: BTreeMap<(String, String), (u64, usize, usize)> = BTreeMap::new();
    for line in FIXTURE.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split_whitespace().collect();
        assert_eq!(f.len(), 4, "malformed fixture line: {line}");
        let (func, prec) = (f[0], f[1]);
        let (err, exact) = match prec {
            "f64" => {
                let x = f64::from_bits(u64::from_str_radix(f[2], 16).unwrap());
                let want = u64::from_str_radix(f[3], 16).unwrap();
                let got = match func {
                    "exp" => vikshep_detmath::exp(x),
                    "ln" => vikshep_detmath::ln(x),
                    "sin" => vikshep_detmath::sin(x),
                    "cos" => vikshep_detmath::cos(x),
                    _ => panic!("unknown function {func}"),
                }
                .to_bits();
                (ulp_distance(got, want, 63), got == want)
            }
            "f32" => {
                let x = f32::from_bits(u32::from_str_radix(f[2], 16).unwrap());
                let want = u32::from_str_radix(f[3], 16).unwrap();
                let got = match func {
                    "exp" => vikshep_detmath::exp_f32(x),
                    "ln" => vikshep_detmath::ln_f32(x),
                    "sin" => vikshep_detmath::sin_f32(x),
                    "cos" => vikshep_detmath::cos_f32(x),
                    _ => panic!("unknown function {func}"),
                }
                .to_bits();
                (
                    ulp_distance(u64::from(got), u64::from(want), 31),
                    got == want,
                )
            }
            _ => panic!("unknown precision {prec}"),
        };
        let e = stats
            .entry((func.to_string(), prec.to_string()))
            .or_insert((0, 0, 0));
        e.0 = e.0.max(err);
        e.1 += usize::from(!exact);
        e.2 += 1;
    }

    let mut measured = Vec::new();
    for ((func, prec), (max_ulp, inexact, n)) in &stats {
        println!(
            "{func:>4} {prec}: n = {n:5}, max error = {max_ulp} ulp, not correctly rounded = {inexact}"
        );
        measured.push((func.as_str(), prec.as_str(), *max_ulp, *inexact));
    }
    let recorded: Vec<_> = RECORDED.to_vec();
    assert_eq!(
        measured, recorded,
        "measured accuracy differs from the recorded table"
    );
}
