#!/usr/bin/env python3
"""Generate correctly rounded reference values for vikshep-detmath.

Writes crates/vikshep-detmath/tests/fixtures/mpmath_reference.txt. Each data
line is

    <function> <precision> <input bits hex> <expected bits hex>

where <precision> is f64 or f32 and <expected> is the correctly rounded
(round-to-nearest-even) value of the exact mathematical function at the
exactly represented input, computed with mpmath at 1300 bits of working
precision (enough for exact argument reduction of any finite binary64 input).

The inputs are drawn from Python's Mersenne Twister with a fixed seed, but
they are written into the fixture as bit patterns, so the fixture (not this
script) is the source of truth. CI does not need mpmath: the fixture is
committed. Re-run this script only to extend the fixture:

    pip install mpmath
    python3 scripts/gen_detmath_fixtures.py
"""

import math
import os
import random
import struct
import sys

import mpmath
from mpmath import mp, mpf

WORK_PREC = 1300
SEED = 20261002
PER_FUNCTION = 2000

FORMATS = {
    # name: (significand bits incl. hidden bit, exponent of smallest subnormal ulp, emax)
    "f64": (53, -1074, 1023),
    "f32": (24, -149, 127),
}

OUT = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "..",
    "crates",
    "vikshep-detmath",
    "tests",
    "fixtures",
    "mpmath_reference.txt",
)


def bits_to_float(fmt, bits):
    if fmt == "f64":
        return struct.unpack("<d", struct.pack("<Q", bits))[0]
    return struct.unpack("<f", struct.pack("<I", bits))[0]


def float_to_bits(fmt, value):
    if fmt == "f64":
        return struct.unpack("<Q", struct.pack("<d", value))[0]
    return struct.unpack("<I", struct.pack("<f", value))[0]


def round_to_format(fmt, x):
    """Round an mpf to the nearest value of the binary format (ties to even)."""
    p, qmin, emax = FORMATS[fmt]
    if mpmath.isinf(x):
        return math.inf if x > 0 else -math.inf
    negative = x < 0
    a = abs(x)
    if a == 0:
        return -0.0 if negative else 0.0
    _, e = mpmath.frexp(a)  # a = m * 2**e with 0.5 <= m < 1
    q = max(e - p, qmin)  # exponent of one ulp at this magnitude
    n = int(mpmath.nint(mpmath.ldexp(a, -q)))
    if n == 0:
        return -0.0 if negative else 0.0
    if n.bit_length() > p:  # rounding carried into the next binade
        n >>= 1
        q += 1
    if q + p - 1 > emax:  # overflow (round-to-nearest overflows to infinity)
        return -math.inf if negative else math.inf
    value = math.ldexp(n, q)  # exact: n has at most p bits
    return -value if negative else value


FUNCTIONS = {
    "exp": mpmath.exp,
    "ln": mpmath.log,
    "sin": mpmath.sin,
    "cos": mpmath.cos,
}


def uniform(rng, lo, hi):
    return lo + (hi - lo) * rng.random()


def to_fmt(fmt, value):
    """Round a Python float to the target format (identity for f64)."""
    return bits_to_float(fmt, float_to_bits(fmt, value))


def random_finite_positive(rng, fmt):
    if fmt == "f64":
        while True:
            b = rng.getrandbits(63)
            if (b >> 52) != 0x7FF:
                return bits_to_float(fmt, b)
    while True:
        b = rng.getrandbits(31)
        if (b >> 23) != 0xFF:
            return bits_to_float(fmt, b)


def inputs_for(rng, func, fmt):
    big = 1.7976931348623157e308 if fmt == "f64" else 3.4028234663852886e38
    xs = []
    if func == "exp":
        lo, hi = (-745.2, 709.8) if fmt == "f64" else (-103.98, 88.73)
        xs += [0.0, -0.0, 1.0, -1.0, 0.5, -0.5, lo, hi, 1e-30, -1e-30]
        xs += [uniform(rng, lo, hi) for _ in range(PER_FUNCTION * 3 // 4)]
        xs += [rng.choice([-1, 1]) * 2.0 ** uniform(rng, -60, 0) for _ in range(PER_FUNCTION // 4)]
    elif func == "ln":
        xs += [1.0, 2.0, 0.5, 10.0, big, 5e-324 if fmt == "f64" else 1.401298464324817e-45]
        xs += [random_finite_positive(rng, fmt) for _ in range(PER_FUNCTION * 3 // 4)]
        xs += [1.0 + rng.choice([-1, 1]) * 2.0 ** uniform(rng, -40, -1) for _ in range(PER_FUNCTION // 4)]
    else:
        xs += [0.0, -0.0, 1.0, -1.0, math.pi / 2, math.pi, 2 * math.pi, 1e22, big]
        xs += [rng.choice([-1, 1]) * 2.0 ** uniform(rng, -30, 30) for _ in range(PER_FUNCTION // 2)]
        xs += [uniform(rng, -10.0, 10.0) for _ in range(PER_FUNCTION // 4)]
        xs += [k * math.pi / 2 for k in range(-40, 41)]
        xs += [
            rng.choice([-1, 1]) * random_finite_positive(rng, fmt)
            for _ in range(PER_FUNCTION // 4 - 81)
        ]
    out = []
    for x in xs:
        if fmt == "f32" and abs(x) > big:
            continue
        out.append(to_fmt(fmt, x))
    return out


def main():
    mp.prec = WORK_PREC
    rng = random.Random(SEED)
    lines = [
        "# Correctly rounded references for vikshep-detmath.",
        "# Generated by scripts/gen_detmath_fixtures.py",
        f"# mpmath {mpmath.__version__}, Python {sys.version.split()[0]}, "
        f"working precision {WORK_PREC} bits, seed {SEED}",
        "# format: function precision input_bits expected_bits",
    ]
    for fmt in ("f64", "f32"):
        width = 16 if fmt == "f64" else 8
        for func in ("exp", "ln", "sin", "cos"):
            for x in inputs_for(rng, func, fmt):
                y = round_to_format(fmt, FUNCTIONS[func](mpf(x)))
                lines.append(
                    f"{func} {fmt} {float_to_bits(fmt, x):0{width}x} "
                    f"{float_to_bits(fmt, y):0{width}x}"
                )
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(lines)} lines to {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
