/*
 * vikshep_backend.h - C ABI of the five VDS-1 Tier-1 kernels.
 * Generated by cbindgen from crates/vikshep-capi/src/lib.rs; do not edit.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026 Samvardhan Singh
 *
 * Memory ownership: the caller owns every buffer; kernels must not retain
 * pointers after returning. VkspComplex32 is { float re; float im; },
 * 8 bytes, alignment 4. Calls are synchronous. See the crate documentation
 * of vikshep-capi and spec/VDS-1.md section 14.6.
 *
 * vksp_register_backend() hands an external table (for example a CUDA or
 * Metal backend built outside this repository) to the library, which then
 * uses it by name in every host function of vikshep.h; see
 * docs/external_backends.md. The status codes below are shared with
 * vikshep.h.
 */

#ifndef VIKSHEP_BACKEND_H
#define VIKSHEP_BACKEND_H

#include <stddef.h>
#include <stdint.h>

// Version of the VkspBackendV1 table layout.
#define VKSP_ABI_VERSION 1

// Success.
#define VKSP_OK 0

// Arguments violate the kernel contract.
#define VKSP_INVALID_ARGUMENT 1

// The device failed.
#define VKSP_DEVICE_ERROR 2

// An output buffer is too small; the required size was written.
#define VKSP_BUFFER_TOO_SMALL 3

// No backend is registered under the requested name.
#define VKSP_UNKNOWN_BACKEND 4

// A backend with that name is already registered (or the name is reserved).
#define VKSP_ALREADY_REGISTERED 5

// The conformance self-test ran and at least one case failed.
#define VKSP_CONFORMANCE_FAILED 6

// Internal error (a caught Rust panic); nothing unwound across the boundary.
#define VKSP_INTERNAL_ERROR 7

// Backend capabilities.
typedef struct VkspCapabilities {
  // Largest log2 transform length per axis.
  uint32_t max_log2_len;
  // Non-zero if canvases are processed in parallel.
  uint8_t parallel;
  // Non-zero if IEEE subnormals are preserved.
  uint8_t preserves_subnormals;
} VkspCapabilities;

// Interleaved binary32 complex value.
typedef struct VkspComplex32 {
  // Real part.
  float re;
  // Imaginary part.
  float im;
} VkspComplex32;

// Canvas shape; `rows == 1` for 1-D.
typedef struct VkspCanvas {
  // Rows (1 for 1-D).
  uint32_t rows;
  // Columns.
  uint32_t cols;
} VkspCanvas;

// Subsampling window in output units:
// `out[b][a][c] = input[b][factor * (offset_rows + a)][factor * (offset_cols + c)].re`.
typedef struct VkspSubsample {
  // Power-of-two factor.
  uint32_t factor;
  // Row offset (0 for 1-D).
  uint32_t offset_rows;
  // Column offset.
  uint32_t offset_cols;
  // Output rows (1 for 1-D).
  uint32_t out_rows;
  // Output columns.
  uint32_t out_cols;
} VkspSubsample;

// A backend: context pointer plus the five kernels and metadata.
typedef struct VkspBackendV1 {
  // Must equal `VKSP_ABI_VERSION`.
  uint32_t abi_version;
  // Backend-owned context passed to every call.
  void *ctx;
  // NUL-terminated backend name, valid as long as the table.
  const char *(*name)(void *ctx);
  // The numerics version implemented.
  uint32_t (*numerics_version)(void *ctx);
  // Capabilities.
  struct VkspCapabilities (*capabilities)(void *ctx);
  // Forward FFT of `batch` canvases in place, with forward tables
  // (`tw_cols`: cols/2 entries; `tw_rows`: rows/2 entries or null).
  int32_t (*fft)(void *ctx,
                 struct VkspComplex32 *data,
                 size_t batch,
                 struct VkspCanvas canvas,
                 const struct VkspComplex32 *tw_cols,
                 const struct VkspComplex32 *tw_rows);
  // Inverse FFT in place, with conjugate tables; each 1-D transform is
  // followed by multiplication with 2^-m.
  int32_t (*ifft)(void *ctx,
                  struct VkspComplex32 *data,
                  size_t batch,
                  struct VkspCanvas canvas,
                  const struct VkspComplex32 *tw_cols,
                  const struct VkspComplex32 *tw_rows);
  // Multiply canvas `b` by filter `index[b]` of `bank` (`n_filters` filters of
  // rows * cols floats): (re, im) -> (re * h, im * h).
  int32_t (*mul_real_filter)(void *ctx,
                             struct VkspComplex32 *data,
                             size_t batch,
                             struct VkspCanvas canvas,
                             const float *bank,
                             size_t n_filters,
                             const uint32_t *index);
  // (re, im) -> (sqrt(re * re + im * im), +0) for len values in place.
  int32_t (*modulus)(void *ctx, struct VkspComplex32 *data, size_t len);
  // `out[b][a][c] = input[b][f * (o_r + a)][f * (o_c + c)].re`.
  int32_t (*subsample)(void *ctx,
                       const struct VkspComplex32 *input,
                       size_t batch,
                       struct VkspCanvas canvas,
                       struct VkspSubsample spec,
                       float *out);
  // Release `ctx`; may be null.
  void (*destroy)(void *ctx);
} VkspBackendV1;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The CPU reference backend as a C table. Call `destroy` when done.
struct VkspBackendV1 vksp_cpu_backend_v1(void);

// Hand an external backend to this library. The table is copied; on
// success the library owns it and calls `destroy` (if non-null) when the
// backend is unregistered and no call is using it. On failure the caller
// keeps ownership. The backend is then available by its `name()` to every
// host function that takes a backend name (`vikshep.h`). Calls into one
// registered backend are serialized by the library.
//
// Requirements: `abi_version == VKSP_ABI_VERSION`, all five kernels and
// `name`/`numerics_version` non-null, `numerics_version()` equal to the
// library's, a name of 1 to 64 bytes other than `cpu` and not yet registered.
//
// # Safety
// `table` must point to a table whose non-null function pointers implement
// the documented contract for its `ctx`.
int32_t vksp_register_backend(const struct VkspBackendV1 *table);

// Remove a registered backend. Its `destroy` runs once no call is using it.
//
// # Safety
// `name` must be a NUL-terminated string.
int32_t vksp_unregister_backend(const char *name);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VIKSHEP_BACKEND_H */
