/*
 * vikshep.h - stable C API of Vikshep compute: scattering, r2, fingerprint,
 * provenance manifest, conformance self-test, version information.
 * Generated by cbindgen from crates/vikshep-capi/src/api.rs; do not edit.
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026 Samvardhan Singh
 *
 * Conventions (see the crate documentation of vikshep-capi):
 * - every function returns a status code (VKSP_OK on success, codes in
 *   vikshep_backend.h); vksp_last_error() describes the last failure on the
 *   calling thread; no Rust panic crosses this boundary;
 * - array outputs use caller-allocated buffers: out_len always receives the
 *   required element count; out == NULL is a size query (returns VKSP_OK);
 *   a short buffer returns VKSP_BUFFER_TOO_SMALL; an empty output is always
 *   computed (its OID is written);
 * - text outputs follow the same protocol in bytes, len excludes the NUL;
 * - OIDs are 28 lowercase hex characters plus a NUL (29 bytes);
 * - backend == NULL selects the CPU reference ("cpu"); other names refer to
 *   backends registered with vksp_register_backend().
 */

#ifndef VIKSHEP_H
#define VIKSHEP_H

#include <stddef.h>
#include <stdint.h>
#include "vikshep_backend.h"

// Version of this host API.
#define VKSP_API_VERSION 1

// Characters of an OID (a buffer needs one more byte for the NUL).
#define VKSP_OID_LEN 28

// Characters of a hex SHA3-256 digest (a buffer needs one more byte).
#define VKSP_SHA3_HEX_LEN 64

// Pad policy: periodic boundary (power-of-two length).
#define VKSP_PAD_CIRCULAR 0

// Pad policy: zero padding with a halo of `2^J` per side.
#define VKSP_PAD_ZERO 1

// Group: keep every path.
#define VKSP_GROUP_TRIVIAL 0

// Group: 2-D, pooled over absolute orientation.
#define VKSP_GROUP_SO2_RELATIVE 1

// Executor recorded in a manifest: the local machine.
#define VKSP_EXECUTOR_LOCAL 0

// Executor recorded in a manifest: a remote worker.
#define VKSP_EXECUTOR_CLOUD 1

// Library version information.
typedef struct VkspVersionInfo {
  // Must equal `sizeof(VkspVersionInfo)`.
  uint32_t struct_size;
  // `VKSP_API_VERSION`.
  uint32_t api_version;
  // `VKSP_ABI_VERSION` of the backend table.
  uint32_t backend_abi_version;
  // Tier-1 numerics version.
  uint32_t numerics_version;
  // Tier-2 algorithm version.
  uint32_t tier2_version;
  // Package version, static NUL-terminated string.
  const char *package_version;
  // Target triple of this build, static NUL-terminated string.
  const char *platform;
} VkspVersionInfo;

// A scattering configuration (VDS-1 section 14.1). Fill it with
// `vksp_config_1d` or `vksp_config_2d`, then adjust fields if needed.
typedef struct VkspScatterConfig {
  // Must equal `sizeof(VkspScatterConfig)`.
  uint32_t struct_size;
  // 1 or 2.
  uint32_t dim;
  // Number of octaves `J`.
  uint32_t j;
  // Wavelets per octave `Q` (1-D; 1 in 2-D).
  uint32_t q;
  // Orientations `L` (2-D, even; 1 in 1-D).
  uint32_t l;
  // Highest order, 1 or 2.
  uint32_t max_order;
  // `VKSP_GROUP_TRIVIAL` or `VKSP_GROUP_SO2_RELATIVE`.
  uint32_t group;
  // First scale kept by r2 (default 1).
  uint32_t carrier_cutoff;
  // Pad policy per axis (rows first; `pad[0]` only in 1-D).
  uint32_t pad[2];
  // Signal shape (rows, cols; `shape[0]` = length in 1-D).
  uint32_t shape[2];
} VkspScatterConfig;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Fill `out` with version information.
//
// # Safety
// `out` points to a `VkspVersionInfo` whose `struct_size` is set.
int32_t vksp_version_info(struct VkspVersionInfo *out);

// Static description of a status code.
const char *vksp_status_string(int32_t status);

// Message of the last failure on this thread (empty if none), under the
// text size-query protocol.
//
// # Safety
// `buf` is null or valid for `cap` writes; `len` is null or valid.
int32_t vksp_last_error(char *buf, size_t cap, size_t *len);

// A 1-D configuration with defaults: trivial group, order 2, carrier
// cutoff 1, `L = 1`.
//
// # Safety
// `out` is valid for one write.
int32_t vksp_config_1d(uint32_t n,
                       uint32_t j,
                       uint32_t q,
                       uint32_t pad,
                       struct VkspScatterConfig *out);

// A 2-D configuration with defaults: order 2, carrier cutoff 1, `Q = 1`.
//
// # Safety
// `out` is valid for one write.
int32_t vksp_config_2d(uint32_t rows,
                       uint32_t cols,
                       uint32_t j,
                       uint32_t l,
                       uint32_t pad_rows,
                       uint32_t pad_cols,
                       uint32_t group,
                       struct VkspScatterConfig *out);

// Validate `cfg` and report its sizes: samples per signal, output paths,
// output samples per path, and r2 ratio pairs (each optional).
//
// # Safety
// `cfg` points to a configuration; outputs are null or valid.
int32_t vksp_scatter_info(const struct VkspScatterConfig *cfg,
                          size_t *signal_len,
                          size_t *n_paths,
                          size_t *out_len,
                          size_t *n_r2);

// OID of `len` raw bytes (29 bytes written to `oid_out`).
//
// # Safety
// `bytes` is valid for `len` reads; `oid_out` for 29 writes.
int32_t vksp_oid(const void *bytes, size_t len, char *oid_out);

// Scattering coefficients of `input_len / signal_len` signals (row-major,
// back to back): `out` receives `[batch][paths][out_len]` binary32 values,
// `oid_out` the OID of their bytes. `backend`: NULL or `"cpu"` for the CPU
// reference, or a registered backend name.
//
// # Safety
// Pointers valid for the documented lengths.
int32_t vksp_scatter(const struct VkspScatterConfig *cfg,
                     const char *backend,
                     const float *input_ptr,
                     size_t input_len,
                     float *out,
                     size_t out_cap,
                     size_t *out_len,
                     char *oid_out);

// r2 ratios (VDS-1 section 14.8) of coefficients produced with `cfg`:
// `[batch][pairs][out_len]` binary32 values.
//
// # Safety
// Pointers valid for the documented lengths.
int32_t vksp_r2(const struct VkspScatterConfig *cfg,
                const float *coeffs,
                size_t coeffs_len,
                float *out,
                size_t out_cap,
                size_t *out_len,
                char *oid_out);

// Log-mean fingerprint (VDS-1 section 14.9) of coefficients produced with
// `cfg`: `[batch][paths]` binary64 values.
//
// # Safety
// Pointers valid for the documented lengths.
int32_t vksp_fingerprint(const struct VkspScatterConfig *cfg,
                         const float *coeffs,
                         size_t coeffs_len,
                         double *out,
                         size_t out_cap,
                         size_t *out_len,
                         char *oid_out);

// Provenance manifest (`spec/provenance.schema.json`) of a scattering run
// of `batch` signals with `cfg`, from the input and output OIDs: canonical
// JSON under the text size-query protocol, and its `manifest_hash` (65
// bytes, may be NULL). `backend_name`/`backend_version` may be NULL (CPU
// reference, this package's version); `executor` is `VKSP_EXECUTOR_LOCAL`
// or `VKSP_EXECUTOR_CLOUD`; wall-clock times are milliseconds since the
// Unix epoch, 0 when not recorded (never part of the hash).
//
// # Safety
// Strings NUL-terminated; buffers valid for their capacities.
int32_t vksp_provenance_manifest(const struct VkspScatterConfig *cfg,
                                 size_t batch,
                                 const char *input_oid,
                                 const char *output_oid,
                                 const char *backend_name,
                                 const char *backend_version,
                                 uint32_t executor,
                                 uint64_t started_unix_ms,
                                 uint64_t finished_unix_ms,
                                 char *json_out,
                                 size_t cap,
                                 size_t *len,
                                 char *hash_out);

// Run the conformance self-test against the compiled-in vectors.
// `subset`: `"quick"` (default when NULL) or `"full"`; `backend`: NULL or
// `"cpu"` for the CPU reference, or a registered backend. Writes the case
// and failure counts, and the JSON report under the text size-query
// protocol (`report_out` may be NULL; a size query still runs the test).
// Returns `VKSP_CONFORMANCE_FAILED` if any case failed.
//
// # Safety
// Strings NUL-terminated; buffers valid for their capacities.
int32_t vksp_conformance_selftest(const char *subset,
                                  const char *backend,
                                  size_t *n_cases,
                                  size_t *n_failed,
                                  char *report_out,
                                  size_t cap,
                                  size_t *len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VIKSHEP_H */
